spring.application.name=dofuschef
spring.datasource.url=jdbc:postgresql://localhost:5432/dofuschef
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

server.servlet.context-path=/api/v1

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

dofusdude.base-path=https://api.dofusdu.de
dofusdude.language=es
dofusdude.game-name=dofus3

jwt.secret=g1tGC/1pkaIU11gHqS+wiHiFadoAX6WXvatOdowfjQo=
jwt.expiration=8640000
